src/src/Entity/Wareneingang.php
<?php

namespace App\Entity;

use App\Entity\AbstractClasses\AbstractEntity;
use App\Entity\Traits\CommonTrait;
use App\Entity\Traits\DateAndUserAddedTrait;
use App\Entity\Traits\FieldAliasTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WareneingangRepository")
 */
class Wareneingang extends AbstractEntity {


    use DateAndUserAddedTrait;
    use FieldAliasTrait;

    const
        TITLE_FOR_COLUMN_ZUTAT = "Zutat",
        TITLE_FOR_COLUMN_CHARGE = "Charge",
        TITLE_FOR_COLUMN_LIEFERSCHEIN = "Lieferschein",
        TITLE_FOR_COLUMN_QUALITATCHECK = "Qualitätscheck",
        TITLE_FOR_COLUMN_MENGE = "Menge",
        TITLE_FOR_COLUMN_LIEFERANT = "Lieferant",
        TITLE_FOR_COLUMN_DATE_ADDED = "Hinzugefüg am",
        TITLE_FOR_COLUMN_USERADDED_ADDED = "Angelegt von";
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Charge;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $Qualitaetscheck;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Menge;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lieferant", inversedBy="wareneingangs")
     */
    protected $Lieferant;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $DateAdded;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="warenannahme")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $UserAdded;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Zutat", inversedBy="wareneingangs")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $Zutat;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $DateEdit;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $EditorId;


    public function getId(): ?int {
        return $this->id;
    }

    public function getCharge(): ?int {
        return $this->Charge;
    }

    public function setCharge(int $Charge): self {
        $this->Charge = $Charge;

        return $this;
    }

    public function getQualitaetscheck(): ?bool {
        return $this->Qualitaetscheck;
    }

    public function setQualitaetscheck(bool $Qualitaetscheck): self {
        $this->Qualitaetscheck = $Qualitaetscheck;

        return $this;
    }

    public function getMenge(): ?int {
        return $this->Menge;
    }

    public function setMenge(int $Menge): self {
        $this->Menge = $Menge;

        return $this;
    }

    public function getLieferant(): ?Lieferant {
        return $this->Lieferant;
    }

    public function setLieferant(?Lieferant $Lieferant): self {
        $this->Lieferant = $Lieferant;

        return $this;
    }

    protected $LieferInt;

    public function setLieferInt(int $lieferInt) {
        $this->LieferInt = $lieferInt;

        return $this;
    }

    public function getLieferInt() {
        return $this->LieferInt;
    }

    public function makeLieferInt($lieferArray) {
        $this->setLieferant($lieferArray[$this->LieferInt]);
    }

    public function reconstructLieferInt($lieferArray) {
        $liefer          = $this->getLieferant();
        $this->LieferInt = $lieferArray[$liefer->getAlias()];
    }


    protected $Inventur;

    public function setInventur(int $inventory) {
        $this->Inventur = $inventory;

        return $this;
    }

    public function getInventur() {
        return $this->Inventur;
    }


    public function getZutat(): ?Zutat {
        return $this->Zutat;
    }

    public function setZutat(?Zutat $Zutat): self {

        $this->Zutat = $Zutat;

        return $this;
    }

    protected $ZutatInt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $Lieferschein;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $ObjectState;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $Identitatsprufung;

    public function setZutatInt($zutatInt) {
        $this->ZutatInt = $zutatInt;

        return $this;
    }

    public function getZutatInt() {
        return $this->ZutatInt;
    }

    public function makeZutatInt($zutatArray) {

        // dump($zutatArray);
        //dump($this->ZutatInt);
        //
        if (is_int($this->ZutatInt)) {
            $this->setZutat($zutatArray[$this->ZutatInt]);
        } else {
            $this->setZutat($this->ZutatInt);
        }
    }

    public function reconstructZutatInt($zutatArray) {
        $zutat = $this->getZutat();

        $this->ZutatInt = $zutatArray[$zutat->getName()];
    }


    public function getLieferschein(): ?string {
        return $this->Lieferschein;
    }

    public function setLieferschein(string $Lieferschein): self {
        $this->Lieferschein = $Lieferschein;

        return $this;
    }


    public function getIdentitatsprufung(): ?bool {
        return $this->Identitatsprufung;
    }

    public function setIdentitatsprufung(bool $Identitatsprufung): self {
        $this->Identitatsprufung = $Identitatsprufung;

        return $this;
    }



    public function getFieldListWithTitles() {
        $result                                         = [];
        $result[self::TITLE_FOR_COLUMN_ZUTAT]           = $this->getZutat()->getName();
        $result[self::TITLE_FOR_COLUMN_CHARGE]          = $this->getCharge();
        $result[self::TITLE_FOR_COLUMN_LIEFERSCHEIN]    = $this->getLieferschein();
        $result[self::TITLE_FOR_COLUMN_QUALITATCHECK]   = $this->getQualitaetscheck();
        $result[self::TITLE_FOR_COLUMN_MENGE]           = $this->getMenge();
        $result[self::TITLE_FOR_COLUMN_LIEFERANT]       = $this->getLieferant()->getAlias();
        $result[self::TITLE_FOR_COLUMN_DATE_ADDED]      = $this->getDateAdded()->format("Y-m-d H:i:s");
        $result[self::TITLE_FOR_COLUMN_USERADDED_ADDED] = $this->getUserAdded()->getDisplayName();


        return $result;
    }
}

src/src/Controller/PDFController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;
use App\Entity\Wareneingang;
use Symfony\Component\HttpFoundation\Request;

class PDFController extends AbstractController
{
    /**
     * @Route("/createpdf/{pItem}", name="pdf")
     */
    public function pdf($pItem, Request $request)
    {

       // Configure Dompdf according to your needs
       $pdfOptions = new Options();
       $pdfOptions->set('defaultFont', 'Arial');
       
       
       // Instantiate Dompdf with our options
       $dompdf = new Dompdf($pdfOptions);
       
       // Retrieve the HTML generated in our twig file
       if($pItem == "Wareneingang"){

        $pName = "Wareneingang";
        $pInternal = "Wareneingang";
        $eingangrepo = $this->getDoctrine()->getRepository(Wareneingang::class);
        $wareneingange = $eingangrepo->findAll();

        $date = $request->query->get('date');
        $date_array = explode(" - ", $date);

        $start_date = explode(".", $date_array[0]);
        $start_date[0] = str_replace('"', "", $start_date[0]);
        $start_date = new \DateTime($start_date[0] . "-" . $start_date[1] . "-". $start_date[2]);
        $end_date = explode(".", $date_array[1]);
        $end_date[2] = str_replace('"', "", $end_date[2]);
        $end_date = new \DateTime($end_date[0] . "-" . $end_date[1] . "-". $end_date[2]);
       
    $headings = ["Lieferant", "Eingangsdatum", "Zutat", "Charge", "Lieferschein", "QC", "Menge", "Bearbeiter", "Unterschrift"];
    $link = ["", "", "", "", "", "", ""];
    $info_array = [];
    $ids = [];
    foreach($wareneingange as $eingang){

        $charge = $eingang->getCharge();
        $lieferschein = $eingang->getLieferschein();
        
        if(!($lieferschein == "INV" && $charge == 0)){
           
            $date = new \DateTime($eingang->getDateAdded()->format('Y-m-d'));
            if($date>=$start_date && $date<=$end_date){
                $items = [];
                array_push($items, $eingang->getLieferant()->getAlias());
                array_push($items, $eingang->getDateAdded()->format('Y-m-d'));
                array_push($items, $eingang->getZutat()->getName());
                array_push($items, $charge);
                array_push($items, $lieferschein);
                array_push($items, ($eingang->getQualitaetscheck() == 1 ? "ok" : "nicht ok"));
                array_push($items, $eingang->getMenge() . $eingang->getZutat()->getEinheit());
         
                    
                
        
        
                
                
                array_push($items, $eingang->getUserAdded()->getDisplayName());
                array_push($items, "img");
                array_push($items, $eingang->getUserAdded()->getSignature());
        
                array_push($ids, $eingang->getId());
              
                array_push($info_array, $items);
             }
           
           
            
        }
      
       
        
    }


        $html = $this->renderView('pdf/Wareneingang.html.twig', [
            'name' => $pName,
            'headings' => $headings,
            'elements' => $info_array,
            'links' => $link,
            'id' => $ids,
        ]);


       }
      
       $dompdf->set_option( 'dpi' , '200' );
       
       // Load HTML to Dompdf
       $dompdf->loadHtml($html);
       
       // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
       $dompdf->setPaper('A4', 'landscape');

       // Render the HTML as PDF
       $dompdf->render();

       // Output the generated PDF to Browser (force download)
       $dompdf->stream($pItem . ".pdf", [
           "Attachment" => true
       ]);
       return new Response(
        '<script>
        window.location = "/panel/{{ item }}";
        </script>'
    );
       
    }
}

src/templates/pdf/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PDFController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/simonstasiuswork/Documents/Tests/Symfony/Test1/test1/src/Controller/PDFController.php'|file_link(0) }}">src/Controller/PDFController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/simonstasiuswork/Documents/Tests/Symfony/Test1/test1/templates/pdf/index.html.twig'|file_link(0) }}">templates/pdf/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

src/templates/pdf/wareneingang.html.twig
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	.
	<style>
		body{
			font-size: 30px;
		}
		table {
			border: 1px solid;
		}

		tr {
			height: 150px;
		}

		td {
			height: 150px;
		}

		th {
			background-color: rgb(165, 165, 165);
		}

		table {
			border-collapse: collapse;
		}

		table, th, td {
			border: 1px solid black;
		}

		.row {
			border: 1px solid black;
			height: 180px;
			position: relative;
			display: inline-block;
			margin-bottom: 20px;
		}

		.logo_container {
			width: 440px;
			background: url("/logo.jpg") no-repeat center center;

			background-size: 300px 400px;
		}

		.headline {
			width: 1240px;
			text-align: center;
		}

		.pageInfo {
			width: 440px;
			padding-left: 6px;

		}

		.pageInfo > p {
			margin-top: 60px;
			margin-left: 20px;
		}

		.pageBreaker {
			page-break-after: always;
		}

		.quad {
			width: 30px;
			height: 30px;
			border: 2px solid black;
		}

		.quad > div {
			padding-left: 50px;
		}

		.select {
			height: 100px;
		}

		.selecter > div > span {
			border: 1px solid black;
			width: 20px;
			height: 20px;
			margin-left: 5px;
		}
		.checkbox{
			font-size: 40px;
		}
		.prufer_container{
			width: 100%;
			height: 100%;
			background-size: 300px 400px;
		}
		.prufer_img{
			width: 200px;
		}
	</style>
	<title>
		Lieferschein
	</title>
</head>
<body>
{% for pageData in wareneingangePages %}
	<div class="logo_container row">
	</div>
	<div class="headline row">
		<h2>Wareneingangskontrolle</h2>
	</div>
	<div class="pageInfo row">
		<p><strong>Seite {{ loop.index }}</strong> von {{ pagesCount }}</p>
	</div>
	<table>
		<tr>
			<th>Datum:</th>
			<th>Lieferant:</th>
			<th>Material/<br/>Rohstoff:</th>
			<th>Lieferschein-<br/>Nummer:</th>
			<th>Chargennummer:</th>
			<th>Optische Sauberkeit der Anlieferungs- einheit, frei von Schädlingen, Schimmel</th>
			<th>Identitätsprüfung Angabe auf dem Lieferschein entsprechen den Angaben auf dem Rohstoff Material</th>
			<th>Maßnahme bei Abweichungen</th>
			<th>Prüfer (Unterschrift):</th>
		</tr>
		{% for wareneingang in pageData %}
			<tr>
				<td>
					{{ wareneingang.DateAdded|date("m.d.Y") }}
					{{ wareneingang.DateAdded|date("H:i") }}
				</td>
				<td>{{ wareneingang.Lieferant.Firmenname }}</td>
				<td>{{ wareneingang.Zutat.Name }}</td>
				<td>{{ wareneingang.Lieferschein }}</td>
				<td>{{ wareneingang.Charge }}</td>
				<td>
					<div class="selecter">
						<input class="checkbox" type="checkbox" {% if wareneingang.qualitaetscheck == true %} checked {% endif %}>
						<span>Ja</span>
						<br>
						<input class="checkbox" type="checkbox" {% if wareneingang.qualitaetscheck != true %} checked {% endif %}>
						<span>Nein</span>
					</div>
				</td>
				<td>
					<div class="selecter">
						<input class="checkbox" type="checkbox" {% if wareneingang.identitatsprufung == true %} checked {% endif %}>
						<span>Ja</span>
						<br>
						<input class="checkbox" type="checkbox" {% if wareneingang.identitatsprufung != true %} checked {% endif %}>
						<span>Nein</span>
					</div>
				</td>
				<td>
					<div class="selecter">
						<div><span>&nbsp;&nbsp;&nbsp;&nbsp;</span> Sperrung</div>
						<div><span>&nbsp;&nbsp;&nbsp;&nbsp;</span> Ablehnung</div>
						<div><span>&nbsp;&nbsp;&nbsp;&nbsp;</span> Sonderfreigabe<br>durch:</div>
						<div><span>&nbsp;&nbsp;&nbsp;&nbsp;</span> Meldung an ...</div>
					</div>
				</td>
				<td>
					<img src="{{  wareneingang.UserAdded.Signature }}" alt="" class="prufer_img">
				</td>
			</tr>
		{% endfor %}
	</table>
	<div class="pageBreaker"></div>
{% endfor %}
</body>
</html>